HW4
ok-technopolis-2021/Kovalenko_Pavel pull request #3
Opened 2021-10-30 20:29 UTC by PaaavelZ

2021-10-30 20:35 UTC, PaaavelZ commented
Визуализацию можно посмотреть тут https://ok-technopolis-2021.github.io/Kovalenko_Pavel/

2021-10-30 20:37 UTC, PaaavelZ commented
В целом по работе: добавил немного адаптивности под ширину экрана, чего давно желал сделать, сделал смену тем полноценной, то бишь добавил цвет всему оставшемуся пространству веб-странички, поманипулировал со сборщиками (не очень удачно)

2021-10-30 20:44 UTC, PaaavelZ commented on dist/index.css
> +:root {
Все dist-файлы хотя и собираются, но на поверку на выходе ерунда, одни alt'ы вместо картинок, стилей вообще нет. Наверно, плохо понял, как строить зависимости, мой index.css юзает стили из src, хотя Вы говорили, что вроде как dist-файлы должны быть самостоятельны, ибо мы их конечному пользователю уже будем подавать, но вот как построить эту независимость - я не очень понял. Получили что получили.

2021-10-30 20:44 UTC, PaaavelZ commented on index.html
> +  <script src="src/change_theme.js" type="module"></script>
Остатки неудачных попыток понять, как подключать "index.js" - у меня по-нормальному никак не получалось, подключать-то он подключал, а вот работать - не работал

2021-10-30 20:44 UTC, PaaavelZ commented on src/index.js
> +import "change_theme.js";
Аналогично, многими способами пытался импортнуть свой "change_theme.js", однако хтмлька не работала (не отзывалась на клик по смене темы). Этот файл в проекте не используется лишь из-за этой проблемы, подключаю "change_themes" напрямую в индекс

2021-10-30 20:49 UTC, PaaavelZ commented
А ещё я так и не понял, зачем мы css файлы обзывали scss - только ради сборщиков?

2021-10-31 07:30 UTC, BusinessDuck requested changes

2021-10-31 07:30 UTC, BusinessDuck commented on dist/index.css
> +@import "../cosmetic/card_right_side.css";
Вот такого не должно быть, все должно собираться в один файл

2021-10-31 07:30 UTC, BusinessDuck commented on gulpfile.js
> +const stylesPath = 'src/styles/**/*.css';
*.scss

2021-10-31 07:30 UTC, BusinessDuck commented on index.html
> +               src="src/assets/tg-logo.png" height="50" alt="TG">
src/assets не превратится в assets/ при сборке, либо искать плагин который так сделает, либо стили оптимистично установить сразу для конечного результата, то есть, _/assets/tg-logo.png_

2021-10-31 07:30 UTC, BusinessDuck commented on index.html
> +  <script src="src/change_theme.js" type="module"></script>
Модулем, это пока слишком современно. Многие клиенты еще не поддерживают это. https://betterprogramming.pub/what-are-cjs-amd-umd-esm-system-and-iife-3633a112db62

посмотри небольшую статью, про типы джаваскрипт файлов. Тебя интересует для браузера iife, прочитай и посмотри как роллап переключить на iife. Также при подключении js, не факт что DOM уже построился, и выбор кнопки из js файла может не работать. 

Используй событие DOMContentLoaded для старта js https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event

2021-10-31 07:30 UTC, BusinessDuck commented on src/index.js
> +import "change_theme.js";
Ответил выше

2021-10-31 07:30 UTC, BusinessDuck commented on src/change_theme.js
> +const PROPS_NAMES = ["-all-page-main-theme", "-left-side-main-theme", "-right-side-main-theme",
что-то мудрено получилось, нужно просто менять класс __dark на body, и от него в стилях уже переопределять

2021-10-31 07:31 UTC, BusinessDuck commented
> А ещё я так и не понял, зачем мы css файлы обзывали scss - только ради сборщиков?

надеюсь, после проверок и чтения комментов все встанет на свои места

2021-11-04 13:13 UTC, BusinessDuck commented
Жду изменений =)

2021-11-07 23:15 UTC, PaaavelZ commented
Извините, я видел все Ваши комментарии, времени пока не было, чтобы исправлять свою работу. В ближайшие дни оживлю свой PR

2021-11-18 12:39 UTC, PaaavelZ commented
Извините, пожалуйста, за такую большую паузу, был очень сильно загружен по другим предметам, разгребал все долги. Сейчас сделал всё так, как требует того задание, всё в дисте собирается в один файл (html, css, js) и всё отображается. С визуализацией через github pages я ещё работаю, из-за перемещения индекса в src он по-простому не отобразит страничку, но тем не менее прикрепляю скриншот из IDE, что всё работает
![image](https://user-images.githubusercontent.com/76079492/142416806-f48587b0-3cd2-4718-bafe-5bb25e820415.png)

2021-11-23 10:18 UTC, BusinessDuck commented on src/styles/index.css
> +@import "reset.scss";
Переименуй в index.scss, добавь в gulp в строке в качестве пути кстилям только "src/stypes/index.scss" -все остальные зависимости он соберет сам так будет более правильно

2021-11-23 10:19 UTC, BusinessDuck commented
С учетом все правок 8.7 Баллов за работу

2021-11-23 10:20 UTC, BusinessDuck approved these changes

2021-11-23 12:58 UTC, PaaavelZ commented
Свернул css-выражения, относящиеся к одному родительскому блоку, везде, где это возможно

2021-11-23 14:01 UTC, PaaavelZ commented
Настроен gh-pages: https://ok-technopolis-2021.github.io/Kovalenko_Pavel/ (слайдер буду дорабатывать, но не факт, что в этой домашке, но своим долгом считаю сделать его адекватным)
Инъекция теперь происходит подключением и развёртыванием index.scss, как Вы и советовали.

2021-11-23 14:03 UTC, merged